### ISSUE TITLE
Error when installing dependencies

### ISSUE THREAD

**Issue by gassio** [andrevvm/wp-vuejs#1]
Hello I am having an issue when installing the dependencies inside _app_ folder:

```
$ npm install
npm ERR! cb() never called!
```

Do you know what is the problem?

**Comment by andrevvm** [comment]
This seems to be related to your current version of NPM, and/or NPM cache.

https://github.com/npm/npm/issues/15344
https://stackoverflow.com/questions/15393821/npm-err-cb-never-called
